# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=38)),
                ('author', models.CharField(max_length=38)),
                ('published_date', models.DateTimeField()),
                ('category', models.CharField(max_length=38)),
            ],
        ),
    ]
