# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-20 21:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='in_print',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
