# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dd4d4a1943936ea88d3efe0384d6628a0cbe89c5d0d5f71a1d3ed445c9d639be411ed1ee735033f1c4bf64a8c0e0960270ba6c941aa2334eb27a5f0a083a698

test:
  secret_key_base: 1ee8be54d541808685a79fef44e9b9141cfeef5cd30fa00f5e46490a2dba1f31e6953330e3040c8281fb4e53f3026f7b981939639ea15ca515d318395470ffdf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
