# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0002_auto_20170621_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courses',
            old_name='course',
            new_name='name',
        ),
    ]
