# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-21 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='in_print',
        ),
        migrations.RemoveField(
            model_name='books',
            name='published_date',
        ),
    ]
