# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-22 00:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=38)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
